repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: flake8
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.3
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
        args: ["--recursive"]
        additional_dependencies: [toml]
        # need to exclude files here as isort in pre-commit hook doesn't seem
        # to look for config in pyproject.toml
<<<<<<< HEAD
        exclude: (rokku\.py|raspberry_pi_camera\/tests\/|raspberry_pi_motion_sensor\/tests\/|raspberry_pi_alarm\/tests)
=======
        exclude: (rokku\.py|raspberry_pi_camera\/tests\/|raspberry_pi_motion_sensor\/tests|raspberry_pi_ui\/utility\.py)
>>>>>>> f7f67e498e37ec299e4907694ebee08a9512401f
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
        args: ["--config", "pyproject.toml"]
        language_version: python3.7