language: python
python:
  - "3.7"
install:
  - pip3 install -r requirements.txt
  - pip3 install flake8
  - pip3 install black
script:
  - flake8 .
  - black --check .
branches:
  only: 
    - master