language: python
python:
  - "3.7"
install:
  - sudo apt-get update
  - sudo apt-get install libcairo2-dev libgirepository1.0-dev gir1.2-gtk-3.0
  - pip3 install -r requirements.txt
  - pip3 install flake8
  - pip3 install black
  - pip3 install fake-rpi
script:
  - flake8 .
  - black --check .
  - python3 -m pytest
branches:
  only: 
    - master
