# Configuring logger
version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: rokku.log
loggers:
  Subscriber:
    level: DEBUG
    handlers: [file, console]
  Publisher:
    level: DEBUG
    handlers: [file, console]
  RPI_IN:
    level: DEBUG
    handlers: [file, console]
  RPI_OUT:
    level: DEBUG
    handlers: [file, console]