[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
line_length = 79
skip = ["rokku.py", "src/raspberry_pi_ui/utility.py", "src/raspberry_pi_intercom/mumble.py"]
skip_glob = ["*/venv/*", "*/raspberry_pi_camera/tests/*", "*/raspberry_pi_motion_sensor/tests/*", "*/raspberry_pi_alarm/tests/*"]
known_future_library = ["future", "pies"]
known_third_party = ["RPi", "fake_rpi", "gi", "googleapiclient", "httplib2", "oauth2client", "paho", "picamera", "publisher", "pytest", "subscriber", "yaml"]
indent = "    "
multi_line_output= 3
include_trailing_comma= "True"
force_grid_wrap= 0
use_parentheses= "True"